name: Rebase Staging on Master and Notify Discord

on:
  push:
    branches:
      - master

jobs:
  rebase_and_notify_discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Rebase staging on master
        id: rebase-staging
        run: |
          git checkout staging
          if ! git rebase master; then
            git rebase --abort
            echo "Merge conflicts detected in the staging branch."
            exit 1
          fi
          git push origin staging

      - name: Send Discord notification on conflicts
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "Merge conflicts detected in the staging branch. Please review and resolve."
